### ISSUE TITLE
Incompatibility with Perl 5.10.1

### ISSUE THREAD

**Issue by eradman** [pgmasters/backrest#108]
I'm trying today's checkout (1afbab) on CentOS 6 which comes with perl 5.10.1. I
installed the following modules:

    cpan -i Net::OpenSSH
    cpan -i IPC::System::Simple
    cpan -i Thread::Queue
    cpan -i JSON::PP

But there seems to be an incompatibility with an edition of Perl this old:

    $ ./test.pl
    Type of arg 1 to keys must be hash (not private variable) at ../lib/BackRest/Ini.pm line 221, near "$oContent)"
    Type of arg 1 to keys must be hash (not hash element) at ../lib/BackRest/Ini.pm line 247, near "})"
    Type of arg 1 to keys must be hash (not private variable) at ../lib/BackRest/Ini.pm line 293, near "$oChecksumContent)"
    Type of arg 1 to keys must be hash (not subroutine entry) at ../lib/BackRest/Ini.pm line 525, near "))"
    Type of arg 1 to keys must be hash (not hash element) at ../lib/BackRest/Ini.pm line 532, near "})"
    Compilation failed in require at ../lib/BackRest/Config.pm line 18.
    BEGIN failed--compilation aborted at ../lib/BackRest/Config.pm line 18.
    Compilation failed in require at ../lib/BackRest/Db.pm line 17.
    BEGIN failed--compilation aborted at ../lib/BackRest/Db.pm line 17.
    Compilation failed in require at ./test.pl line 22.
    BEGIN failed--compilation aborted at ./test.pl line 22.

**Comment by dwsteele** [comment]
It looks like the way I'm using keys() is not supported below 5.12.  That's a bummer because I use this pattern a lot and it may be hard to redo all the code that uses it.

I've seen a lot of complaints about this version of Perl shipping with CentOS 6 / RHEL 6.  For now I've documented the version requirement but I'll think about how to fix it going forward.

**Comment by terrorobe** [comment]
At the very least introducing a hard "require" for a specific minimum version so that users get a more helpful error message.

Wondering if there are modules which emulate the behaviour on older versions - http://search.cpan.org/~sharyanto/Syntax-Feature-EachOnArray-0.04/lib/Syntax/Feature/KeysOnArray.pm maybe?

**Comment by dwsteele** [comment]
I actually have it working on 5.10.1 now (see dev_keys branch).  Just working on some CentOS docs before I commit to dev branch.
My ultimate goal is to not rely on CPAN for any major enterprise OS.  CentOS/RHEL 6 definitely falls into that category.

**Comment by dwsteele** [comment]
Fixed in 61dfeca and regression tests run.  Plus, I've added docs for CentOS 6 and for setting up regression tests.
Please have another try and see how it goes.

**Comment by eradman** [comment]
The `dev` branch seems to work on Cent6 now. Next I'll try running some real backups. Thanks!

**Comment by dwsteele** [comment]
Excellent, let me know how that goes.
If you need a release version for production I can create one at any time based on what's in dev.
